# Generated by Django 2.1.7 on 2019-03-15 16:07

from django.db import migrations

def seed_required_key_val(apps, schema_editor):
    Config = apps.get_model('store', 'Config')

    # All store page configs.
    Config.objects.create(key='DEFAULT_ALL_STORE_WELCOME_ENGLISH', value='Welcome people from')
    Config.objects.create(key='DEFAULT_ALL_STORE_WELCOME_ARABIC', value='الله حييكم يا أهل')


def seed_required_key_val_image(apps, schema_editor):
    Config = apps.get_model('store', 'DefaultImage')

    # All store page configs.
    Config.objects.create(key='DEFAULT_CITY_IMAGE', value='/default/image.jpg')
    Config.objects.create(key='DEFAULT_STORE_IMAGE', value='/default/store.jpg')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_required_key_val),
        migrations.RunPython(seed_required_key_val_image),
    ]
