# Generated by Django 2.1.7 on 2019-04-29 07:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190315_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='distance_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326),
        ),
    ]
