# Generated by Django 2.2.4 on 2019-09-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
        ('store', '0003_store_distance_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='arabic_font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.ArabicFont'),
        ),
        migrations.AddField(
            model_name='city',
            name='arabic_font_color',
            field=models.CharField(blank=True, help_text='Color in HEX format. \n ex: f1f1f1', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='arabic_font_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='arabic_font_style',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='arabic_font_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='english_font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.EnglishFont'),
        ),
        migrations.AddField(
            model_name='city',
            name='english_font_color',
            field=models.CharField(blank=True, help_text='Color in HEX format. \n ex: f1f1f1', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='english_font_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='english_font_style',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='english_font_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='arabic_font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.ArabicFont'),
        ),
        migrations.AddField(
            model_name='store',
            name='arabic_font_color',
            field=models.CharField(blank=True, help_text='Color in HEX format. \n ex: f1f1f1', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='arabic_font_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='arabic_font_style',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='arabic_font_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='english_font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.EnglishFont'),
        ),
        migrations.AddField(
            model_name='store',
            name='english_font_color',
            field=models.CharField(blank=True, help_text='Color in HEX format. \n ex: f1f1f1', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='english_font_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='english_font_style',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='english_font_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
