# Generated by Django 2.2.4 on 2019-09-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190913_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='arabic_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.ArabicFont'),
        ),
        migrations.AlterField(
            model_name='store',
            name='english_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.EnglishFont'),
        ),
    ]
