# Generated by Django 2.2.4 on 2019-09-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190913_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='arabic_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.ArabicFont'),
        ),
        migrations.AlterField(
            model_name='city',
            name='english_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.EnglishFont'),
        ),
    ]
