# Generated by Django 2.2.4 on 2019-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190913_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='arabic_font',
        ),
        migrations.RemoveField(
            model_name='store',
            name='arabic_font_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='arabic_font_size',
        ),
        migrations.RemoveField(
            model_name='store',
            name='arabic_font_style',
        ),
        migrations.RemoveField(
            model_name='store',
            name='arabic_font_weight',
        ),
        migrations.RemoveField(
            model_name='store',
            name='english_font',
        ),
        migrations.RemoveField(
            model_name='store',
            name='english_font_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='english_font_size',
        ),
        migrations.RemoveField(
            model_name='store',
            name='english_font_style',
        ),
        migrations.RemoveField(
            model_name='store',
            name='english_font_weight',
        ),
    ]
