# Generated by Django 2.2.4 on 2019-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190914_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='arabic_line_height',
            field=models.FloatField(blank=True, default=5, help_text='Line Height in REM', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='english_line_height',
            field=models.FloatField(blank=True, default=5, help_text='Line Height in REM', null=True),
        ),
    ]
