# Generated by Django 2.2.6 on 2019-10-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
        ('store', '0008_auto_20190916_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultimage',
            options={'verbose_name': 'Default Image', 'verbose_name_plural': 'Default Images'},
        ),
        migrations.CreateModel(
            name='DefaultFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('english_font_size', models.FloatField()),
                ('english_font_weight', models.PositiveSmallIntegerField()),
                ('english_font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20)),
                ('english_font_color', models.CharField(help_text='Color in HEX format. \n ex: f1f1f1', max_length=6)),
                ('english_line_height', models.FloatField(default=5, help_text='Line Height in REM')),
                ('arabic_font_size', models.FloatField()),
                ('arabic_font_weight', models.PositiveSmallIntegerField()),
                ('arabic_font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic'), ('oblique', 'Oblique')], max_length=20)),
                ('arabic_font_color', models.CharField(help_text='Color in HEX format. \n ex: f1f1f1', max_length=6)),
                ('arabic_line_height', models.FloatField(default=5, help_text='Line Height in REM')),
                ('arabic_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.ArabicFont')),
                ('english_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.EnglishFont')),
            ],
            options={
                'verbose_name': 'Default Font',
                'verbose_name_plural': 'Default Fonts',
            },
        ),
    ]
