# Generated by Django 2.2.6 on 2020-01-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20191020_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('name_in_arabic', models.CharField(max_length=120, unique=True)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegionSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('name_in_arabic', models.CharField(max_length=120, unique=True)),
                ('lat', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RegionCategory')),
            ],
        ),
    ]
