# Generated by Django 2.2.6 on 2020-04-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_regioncategory_regionsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regioncategory',
            options={'ordering': ('name', 'name_in_arabic'), 'verbose_name': 'Region Category', 'verbose_name_plural': 'Region Categories'},
        ),
        migrations.AlterModelOptions(
            name='regionsubcategory',
            options={'ordering': ('name', 'name_in_arabic'), 'verbose_name': 'Region Sub Category', 'verbose_name_plural': 'Region Sub Categories'},
        ),
    ]
