# Generated by Django 2.2.6 on 2020-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200412_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regioncategory',
            options={'ordering': ('name', 'name_in_bnabic'), 'verbose_name': 'Region Category', 'verbose_name_plural': 'Region Categories'},
        ),
        migrations.AlterModelOptions(
            name='regionsubcategory',
            options={'ordering': ('name', 'name_in_bnabic'), 'verbose_name': 'Region Sub Category', 'verbose_name_plural': 'Region Sub Categories'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_font',
            new_name='bangla_font',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_font_color',
            new_name='bangla_font_color',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_font_size',
            new_name='bangla_font_size',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_font_style',
            new_name='bangla_font_style',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_font_weight',
            new_name='bangla_font_weight',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='arabic_line_height',
            new_name='bangla_line_height',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_in_ar',
            new_name='name_in_bn',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='welcome_message_in_arabic',
            new_name='welcome_message_in_bangla',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_font',
            new_name='bangla_font',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_font_color',
            new_name='bangla_font_color',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_font_size',
            new_name='bangla_font_size',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_font_style',
            new_name='bangla_font_style',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_font_weight',
            new_name='bangla_font_weight',
        ),
        migrations.RenameField(
            model_name='defaultfont',
            old_name='arabic_line_height',
            new_name='bangla_line_height',
        ),
        migrations.RenameField(
            model_name='regioncategory',
            old_name='name_in_arabic',
            new_name='name_in_bnabic',
        ),
        migrations.RenameField(
            model_name='regionsubcategory',
            old_name='name_in_arabic',
            new_name='name_in_bnabic',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address_in_ar',
        ),
        migrations.RemoveField(
            model_name='store',
            name='distributor_name_in_ar',
        ),
        migrations.AddField(
            model_name='store',
            name='address_in_bn',
            field=models.TextField(default='', max_length=1000, verbose_name='Address in Bangla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='distributor_name_in_bn',
            field=models.CharField(default='', help_text='Distributor name in Bangla', max_length=250),
            preserve_default=False,
        ),
    ]
