# Generated by Django 2.2.6 on 2020-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200412_1309'),
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArabicFont',
            new_name='BanglaFont',
        ),
    ]
